### ISSUE TITLE
feast-hive plugin not working on hive with backend as tez

### ISSUE THREAD

**Issue by itsmesrds** [baineng/feast-hive#12]
recently i have encounter the issue below, when I'm using hive as offline store for feast (hive runs on tez)

there is no issue in using (hive runs on mr) but the capability of using hive on mr is deprecated in >= hive 2.7.x and not available in hive 3.x (so its should execute on tez)

When its trying to run the any join command with impala hive package
```
city:
Traceback (most recent call last):
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast/cli.py", line 391, in materialize_command
    store.materialize(
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast/usage.py", line 210, in exception_logging_wrapper
    result = func(*args, **kwargs)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast/feature_store.py", line 755, in materialize
    provider.materialize_single_feature_view(
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 117, in materialize_single_feature_view
    table = offline_job.to_arrow()
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast/infra/offline_stores/offline_store.py", line 66, in to_arrow
    return self._to_arrow_internal()
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast_hive/hive.py", line 314, in _to_arrow_internal
    return pa.Table.from_batches(pa_batches, schema)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/impala/interface.py", line 179, in __exit__
    reraise(exc_type, exc_val, exc_tb)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/feast_hive/hive.py", line 302, in _to_arrow_internal
    cursor.execute(query)
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/impala/hiveserver2.py", line 343, in execute
    self._wait_to_finish()  # make execute synchronous
  File "/Users/itsmesrds/Desktop/feast-trail/feast-env/lib/python3.8/site-packages/impala/hiveserver2.py", line 427, in _wait_to_finish
    raise OperationalError(resp.errorMessage)
impala.error.OperationalError: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask
```

and the join queries are working fine with pyhive package. @baineng  just want to know is there any specific reason why we use impyla instead of pyhive ?

To replicate, you can create EMR >= 6 version or hive >=3.X

**Comment by baineng** [comment]
Hi @itsmesrds, first of all, thanks for reporting this.

Actually I have tested on Hive 3.0 with Spark as a execution engine, I haven't tried it on tez. Could you post more details about the error on tez? which can help to identify the issue.

I kind of forget why I choose impyla instead of pyhive, I did try both and I thought impyla was more suitable here and it's more actively developing than pyhive.
Anyway, I don't think here is related to impyla or pyhive, it's the error happened on tez side.

**Comment by baineng** [comment]
Close this since no update.
