### ISSUE TITLE
feast apply error

### ISSUE THREAD

**Issue by azydon** [baineng/feast-hive#21]
Feast SDK Version: "feast 0.23.2"
Traceback (most recent call last):
  File "/home/azy/.local/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/home/azy/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/azy/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/azy/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/azy/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azy/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/azy/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/azy/.local/lib/python3.10/site-packages/feast/cli.py", line 495, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/home/azy/.local/lib/python3.10/site-packages/feast/usage.py", line 287, in wrapper
    raise exc.with_traceback(traceback)
  File "/home/azy/.local/lib/python3.10/site-packages/feast/usage.py", line 276, in wrapper
    return func(*args, **kwargs)
  File "/home/azy/.local/lib/python3.10/site-packages/feast/repo_operations.py", line 304, in apply_total
    project, registry, repo, store = _prepare_registry_and_repo(repo_config, repo_path)
  File "/home/azy/.local/lib/python3.10/site-packages/feast/repo_operations.py", line 202, in _prepare_registry_and_repo
    repo = parse_repo(repo_path)
  File "/home/azy/.local/lib/python3.10/site-packages/feast/repo_operations.py", line 119, in parse_repo
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/feast_test/feature_repo/example.py", line 11, in <module>
    driver_hourly_stats = HiveSource(
  File "/home/azy/.local/lib/python3.10/site-packages/feast_hive/hive_source.py", line 94, in __init__
    super().__init__(
  File "/home/azy/.local/lib/python3.10/site-packages/typeguard/__init__.py", line 1031, in wrapper
    memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
  File "/home/azy/.local/lib/python3.10/site-packages/typeguard/__init__.py", line 198, in __init__
    self.arguments = signature.bind(*args, **kwargs).arguments
  File "/usr/lib/python3.10/inspect.py", line 3179, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3105, in _bind
    raise TypeError(
TypeError: too many positional arguments

**Comment by stephyi** [comment]
+1

**Comment by qywang2012** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
oliver-zehentleitner, @Jerryblessed, @jeremylinnn, @pingwping, @slimorder, @ironbox1995, @ijoywan, @HXhlx, @whitespur, @roy-tang-hs, @hahaguo, @MarsOu1995, @sangtrx, @safequant, @biglyan, @dancingonmoon, @laolooong, @Bbingbing, @TheHooper, @afirez
